Transform: 'AWS::Serverless-2016-10-31'

Parameters:

  Env:
    Type: String
    Description: Environment
    AllowedValues: [prd, stg, itg]
    ConstraintDescription: must specify prd, stg or itg.
    Default: itg

  DomainName:
    Type: String
    Description: Custom Domain Name

  CertificateArn:
    Type: String
    Description: Certificate Arn

Resources:
  ResizeImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      Timeout: 180
      CodeUri: ./src
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ImageProcessingApi
            Path: /resize
            Method: GET

  ImageProcessingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      DefinitionBody:
        swagger: 2.0
        info:
          title: !Sub image-processing-api-${Env}
          description: !Sub image-processing-api-${Env}
          version: 1.0.0
        schemes:
          - https
        basePath: !Sub /${Env}
        paths:
          /resize:
            get:
              produces:
                - application/json
              parameters:
                - name: url
                  in: query
                  description: Original Image URL
                  required: true
                  type: string
                - name: w
                  in: query
                  description: Width
                  required: true
                  type: integer
                - name: h
                  in: query
                  description: Height
                  required: true
                  type: integer
                - name: t
                  in: query
                  description: Content-Type (jpeg, png, gif, webp)
                  required: true
                  type: string
              responses: {}
              x-amazon-apigateway-integration:
                httpMethod: POST
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResizeImageFunction.Arn}/invocations
                type: aws_proxy
        x-amazon-apigateway-binary-media-types: ['application/octet-stream', 'image/jpeg', 'image/png', 'image/gif', 'image/webp']

  CustomDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref CertificateArn
      DomainName: !Ref DomainName

  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref CustomDomainName
      RestApiId: !Ref ImageProcessingApi
      Stage: !Ref Env

Outputs:
  ResizeImageFunction:
    Description: Resize Image Function
    Value: !Ref ResizeImageFunction
  ImageProcessingApi:
    Description: Image Processing Api Endpoint
    Value: !Ref ImageProcessingApi
